spring.application.name=api-gateway
server.port=8765

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Spring Cloud Gateway Configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
# done using class

# spring.cloud.gateway.routes[0].id=patient-service
# spring.cloud.gateway.routes[0].uri=lb://patient-service
# spring.cloud.gateway.routes[0].predicates[0]=Path=/patient/**
# spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
# spring.cloud.gateway.routes[1].id=doctor-service
# spring.cloud.gateway.routes[1].uri=lb://doctor-service
# spring.cloud.gateway.routes[1].predicates[0]=Path=/doctor/**
# spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
# spring.cloud.gateway.routes[2].id=appointment-service
# spring.cloud.gateway.routes[2].uri=lb://appointment-service
# spring.cloud.gateway.routes[2].predicates[0]=Path=/appointment/**
# spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
